### PR TITLE
created a page for label with dummy content

### PR DESCRIPTION
**Pull request by vidhi-thakur**
image

### CODE REVIEW

**Review by sonishreyas — APPROVED** [review]
Code looks good. Just check why the checks are failing

**Review by manojasarsa — APPROVED** [review]
The code seems clean and UI is also good.
GTG!

**Comment by vidhi-thakur** [comment]
> The code seems clean and UI is also good. GTG!

thanks for your review

**Comment by vidhi-thakur** [comment]
> Code looks good. Just check why the checks are failing

thanks for your review, it was an unused import

**Pull request merged**
